### ISSUE TITLE
System Volume Information

### ISSUE THREAD

**Issue by denis28381** [edkennard/rekordbox-repair#12]
2022-01-23 20:01:49,124 ERROR - Failed to complete successfully: java.nio.file.AccessDeniedException: F:\System Volume Information
java.io.UncheckedIOException: java.nio.file.AccessDeniedException: F:\System Volume Information
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
        at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
        at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
        at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:43)
        at scala.collection.Iterator.toStream(Iterator.scala:1415)
        at scala.collection.Iterator.toStream$(Iterator.scala:1414)
        at scala.collection.AbstractIterator.toStream(Iterator.scala:1429)
        at scala.collection.Iterator.$anonfun$toStream$1(Iterator.scala:1415)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
        at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
        at scala.collection.immutable.Stream.filterImpl(Stream.scala:506)
        at scala.collection.immutable.Stream$.$anonfun$filteredTail$1(Stream.scala:1258)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
        at scala.collection.immutable.Stream.length(Stream.scala:312)
        at scala.collection.SeqLike.size(SeqLike.scala:108)
        at scala.collection.SeqLike.size$(SeqLike.scala:108)
        at scala.collection.AbstractSeq.size(Seq.scala:45)
        at com.vividlab.rekordbox.analyse.Analyser$.locateFile(Analyser.scala:74)
        at com.vividlab.rekordbox.analyse.Analyser$.$anonfun$locateFiles$1(Analyser.scala:52)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike.map(TraversableLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.immutable.List.map(List.scala:298)
        at com.vividlab.rekordbox.analyse.Analyser$.locateFiles(Analyser.scala:52)
        at com.vividlab.rekordbox.analyse.Analyser$.analyse(Analyser.scala:31)
        at com.vividlab.rekordbox.Main$.main(Main.scala:15)
        at com.vividlab.rekordbox.Main.main(Main.scala)
Caused by: java.nio.file.AccessDeniedException: F:\System Volume Information
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
        at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:518)
        at java.nio.file.Files.newDirectoryStream(Files.java:457)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
        at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:95)
        ... 36 common frames omitted

**Comment by edkennard** [comment]
Hi @denis28381 , sorry it took me a while to get back to you.

It looks like you may have told the tool to scan your entire hard disk (F:), which in turn may have failed to access certain system directories you're locked out of by default (F:\System Volume Information). The solution would be to specify a folder within drive F:

Cheers

Ed

**Comment by denis28381** [comment]
Can i somehow specify for the tool not to reed sys vol info because drive F is my music drive and there are many folders with music in it

**Comment by edkennard** [comment]
OK, I will make a change to the tool this evening so it'll just ignore directories it can't access, I should have done it that way in the first place. Will let you know when a new version is published

**Comment by denis28381** [comment]
Ok thank you very much

**Comment by edkennard** [comment]
@denis28381 Pls try this version and let me know if it's ok now: https://github.com/edkennard/rekordbox-repair/releases/tag/v0.4

**Comment by denis28381** [comment]
Same haven't fixed it 


ERROR - Failed to complete successfully: java.nio.file.AccessDeniedException: F:\System Volume Information
java.io.UncheckedIOException: java.nio.file.AccessDeniedException: F:\System Volume Information
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
        at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
        at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
        at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:43)
        at scala.collection.Iterator.toStream(Iterator.scala:1415)
        at scala.collection.Iterator.toStream$(Iterator.scala:1414)
        at scala.collection.AbstractIterator.toStream(Iterator.scala:1429)
        at scala.collection.Iterator.$anonfun$toStream$1(Iterator.scala:1415)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
        at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
        at scala.collection.immutable.Stream.filterImpl(Stream.scala:506)
        at scala.collection.immutable.Stream$.$anonfun$filteredTail$1(Stream.scala:1258)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
        at scala.collection.immutable.Stream.length(Stream.scala:312)
        at scala.collection.SeqLike.size(SeqLike.scala:108)
        at scala.collection.SeqLike.size$(SeqLike.scala:108)
        at scala.collection.AbstractSeq.size(Seq.scala:45)
        at com.vividlab.rekordbox.analyse.Analyser$.locateFile(Analyser.scala:74)
        at com.vividlab.rekordbox.analyse.Analyser$.$anonfun$locateFiles$1(Analyser.scala:52)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike.map(TraversableLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.immutable.List.map(List.scala:298)
        at com.vividlab.rekordbox.analyse.Analyser$.locateFiles(Analyser.scala:52)
        at com.vividlab.rekordbox.analyse.Analyser$.analyse(Analyser.scala:31)
        at com.vividlab.rekordbox.Main$.main(Main.scala:15)
        at com.vividlab.rekordbox.Main.main(Main.scala)
Caused by: java.nio.file.AccessDeniedException: F:\System Volume Information
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
        at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:518)
        at java.nio.file.Files.newDirectoryStream(Files.java:457)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
        at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
        at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:95)
        ... 36 common frames omitted

**Comment by edkennard** [comment]
@denis28381 Hi Denis, the stack trace you posted today is completely identical to the one you originally posted in January, which leads me to believe you're not using the latest version 0.4.

Please could you check 100% that you are using the latest version? An easy way to know that is by looking at the log output and checking whether after the line saying "Checking playlists..." it either says "Locating files referenced by tracks in the collection..." (old version) or "Listing audio and video files in the search directory" (new version)

Thanks
