### ISSUE TITLE
doesn't recognise -s function

### ISSUE THREAD

**Issue by treemi** [edkennard/rekordbox-repair#22]
Hey - thanks so much for making this - much more practical than the inbuilt rekordbox feature, especially for large libraries. 

The problem im having is that the terminal doesn't seem to recognise the -s function: 

imis-MacBook-Pro:rekordbox-repair-0.5 thor$ bin/rekordbox-repair -i "/Users/thor/Downloads/rekordbox/library.xml" -o "/Users/thor/Downloads/rekordbox/fixed-library.xml" -s "/Volumes/T7 Shield/Music"
2023-11-07 23:58:00,577 INFO  - Running using Java version 1.8.0_211
Error: Unknown option -s /Volumes/T7 Shield/Music
Try --help for more information.
Exception in thread "main" java.lang.IllegalStateException: Failed to read configuration: -i, /Users/thor/Downloads/rekordbox/library.xml, -o, /Users/thor/Downloads/rekordbox/fixed-library.xml, -s /Volumes/T7 Shield/Music
	at com.vividlab.rekordbox.Config$.apply(Config.scala:55)
	at com.vividlab.rekordbox.Main$.main(Main.scala:13)
	at com.vividlab.rekordbox.Main.main(Main.scala)

What am I doing wrong?

**Comment by edkennard** [comment]
@treemi Hey, sorry for late reply, I think you should put double quotes around the search path, since it has a space in it?

**Comment by edkennard** [comment]
@treemi Sorry, I can see actually you already did that. Will do a test later and get back to you..
