### ISSUE TITLE
error message, please help

### ISSUE THREAD

**Issue by mungbean123** [edkennard/rekordbox-repair#8]
2021-01-21 17:03:20,175 INFO  - Generating repaired rekordbox collection...
2021-01-21 17:03:20,406 INFO  - Transforming XML...
2021-01-21 17:03:22,037 INFO  - Saving new XML to D:\Games...
Exception in thread "main" java.io.FileNotFoundException: D:\Games (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at scala.xml.XML$.save(XML.scala:92)
        at com.vividlab.rekordbox.repair.Repairer$.repair(Repairer.scala:23)
        at com.vividlab.rekordbox.Main$.main(Main.scala:19)
        at com.vividlab.rekordbox.Main.main(Main.scala)
        
        
        ive run cmd in admin, not much knowledge of code but relatively tech savvy 
        not sure why it cant access the output file 
        any help would be magic

**Comment by edkennard** [comment]
Hey @mungbean123 , the output file should be an XML file, e.g. D:\Games\fixed.xml.  I think you might have specified the output to be "D:\Games" instead of "D:\Games\fixed.xml" ?
